### ISSUE TITLE
Combine efforts

### ISSUE THREAD

**Issue by kelunik** [WyriHaximus/reactphp-async-interop-loop#6]
There's another adapter, maybe you can combine efforts: https://github.com/voryx/ReactLoopInterfaceForAsyncInteropLoop

**Comment by WyriHaximus** [comment]
Yeah noticed that @davidwdan and @mbonneau started working on that. Haven't reached out to them yet though. Thanks for the heads up 👍

**Comment by davidwdan** [comment]
@kelunik  We most certainly can combine efforts, however ours is more of a reverse adapter, so you can use any interop loop with libs that require ReactPHP.

**Comment by kelunik** [comment]
@davidwdan I guess that's the adapter we really need, because in the future, more and more libraries will only be based on the interop loop I guess. This one includes adapters for both directions I think.

**Comment by davidwdan** [comment]
We totally missed that!  @WyriHaximus anyway that you can tag a prerelease?

**Comment by WyriHaximus** [comment]
@kelunik correct :+1: 
@davidwdan sure, it's only a `git tag -s` away. I'll update the readme first :smile:

**Comment by WyriHaximus** [comment]
Ow and I'll merge the two PR's as well before tagging

**Comment by WyriHaximus** [comment]
FYI I've merged @kelunik and mine PR's and tagged [`0.1.0`](https://github.com/WyriHaximus/reactphp-async-interop-loop/releases/tag/0.1.0)

**Comment by davidwdan** [comment]
:+1:  Thank you!

**Comment by WyriHaximus** [comment]
No problem!

**Comment by davidwdan** [comment]
@WyriHaximus You can probably close this issue
